language: python
sudo: true
python:
    - "3.6"

services:
  - docker

install:
    - pip install tox-travis

# elasticsearch constraint
before_script:
  - sudo sysctl -w vm.max_map_count=262144

script:
    - tox
